#
# Module manifest for module 'MtdModules'
#
# Generated by: Ryan Blackman
#
# Generated on: 6/23/2015
#

@{

# Version number of this module.
ModuleVersion = '1.1'

# ID used to uniquely identify this module
GUID = '5b8b77c6-fbf3-4c96-9b6b-0f52cdb363a4'

# Author of this module
Author = 'Ryan Blackman'

# Company or vendor of this module
CompanyName = 'Champaign-Urbana Mass Transit District'

# Copyright statement for this module
Copyright = '(c) 2016 Champaign-Urbana Mass Transit District. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Utility modules for managing MTD computers.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Remove-RemoteConnections.psm1', 'Restart-AppPool.psm1', 'Redo-SharedCalendarPermission.psm1', 'Enable-LitigationHold.psm1', 'Move-HomeDirectories.psm1', 'Hide-MailboxFromGAL.psm1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/CUMTD/PowershellManagementScripts'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
DefaultCommandPrefix = 'Mtd'

}
